--- #YAML:1.0
name:                CPAN-Testers-WWW-Reports-Query-Reports
version:             0.10
abstract:            Retrieve CPAN Testers metadata direct from the CPAN Testers website.
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                   5.006
  JSON::XS:               0
  WWW::Mechanize:         0
recommends:
  Test::CPAN::Meta:       0
  Test::CPAN::Meta::JSON: 0
  Test::MockObject:       0
  Test::Pod:              1.00
  Test::Pod::Coverage:    0.08
build_requires:
  IO::File:               0
  Test::More:             0.70

provides:
  CPAN::Testers::WWW::Reports::Query::Reports:
    file:     lib/CPAN/Testers/WWW/Reports/Query/Reports.pm
    version:  0.10

resources:
  homepage:   https://www.cpantesters.org
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=CPAN-Testers-WWW-Reports-Query-Reports
  repository: http://github.com/barbie/cpan-testers-www-reports-query-reports

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: The Hand of Barbie 1.0
